production:
  database: dashboard
  username: dashboard
  password: dashboard
  encoding: utf8
  adapter: mysql

development:
  database: dashboard_development
  username: dashboard
  password: dashboard
  encoding: utf8
  adapter: mysql

test:
  database: dashboard_test
  username: dashboard
  password: dashboard
  encoding: utf8
  adapter: mysql
